name: Benchmarks

on:
  push:
  pull_request:
    types: [synchronize, labeled]
  workflow_dispatch:
  merge_group:
env:
  PYTHON_VERSION: "3.10"
  BENCHMARKS_DIR: ${{ github.workspace }}/benchmarks/python
  BENCHMARKS_OUTPUT: ${{ github.workspace }}/benchmarks_output
  CARGO_NET_GIT_FETCH_WITH_CLI: true


permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write
  # allow posting comments to pull request
  pull-requests: write

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  Criterion:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'run-benchmarks') || github.event_name == 'push' || github.event_name == 'merge_group' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203
        with:
          toolchain: stable

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ runner.group }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.group }}-rust-
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - name: Install cargo-criterion if not cached
        run: |
          if ! command -v cargo-criterion &> /dev/null; then
            echo "cargo-criterion is not found, installing..."
            cargo install cargo-criterion
          else
            echo "cargo-criterion is cached"
          fi

      - name: Run benchmarks
        run: cargo criterion --bench criterion --output-format bencher|& tee benchmarks.txt

      - name: Compare benchmarks
        uses: 414owen/github-action-benchmark@97047c8ae34c7d34cff8ccca39705d2f72c53fa0
        with:
          tool: 'cargo'
          output-file-path: benchmarks.txt
          alert-threshold: "110%"
          fail-on-alert: ${{ github.event_name == 'pull_request' }}
          comment-on-alert: ${{ github.event.pull_request.head.repo.fork == false }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          auto-push: ${{ github.event_name == 'push' }}
          save-data-file: ${{ github.event_name == 'push' }}
